Monorepo + fixes
RoboJackets/robocup-firmware pull request #156
Opened 2022-05-12 20:18 UTC by kasohrab

2022-05-13 09:23 UTC, Arvind-Srinivasan requested changes
I'll come back and look at approving this once we can confirm robots run in shop with the main build.

2022-05-13 09:35 UTC, Arvind-Srinivasan requested changes
Before we can merge, a) bunch of minor comments, b) cleaning up the file structure, c) the doxygen docs building should work on the whole, and d) the includes should be cleaned up.

First and foremost, every single test from the mtrain level up should work and imo, we should write even more tests to use as regression benchmarks. Would be good to know every API works for example using control. We should also clean up the tests in control level to have only the most recent hardware tests (I.E. get rid of the ones for an IMU we no longer have)

2022-05-13 09:35 UTC, Arvind-Srinivasan commented on control/include/drivers/AVR910.hpp
>  #include <cstdio>
Stuff like this should be in our standard robocup.hpp file

2022-05-13 09:35 UTC, Arvind-Srinivasan commented on control/include/drivers/ICM20948.hpp
> +#include <cmath>
Same with these

2022-05-13 09:35 UTC, Arvind-Srinivasan commented on control/include/drivers/ISM43340.hpp
> +#include <cstdio>
Move to robocup.hpp the standard lib includes

2022-05-13 09:35 UTC, Arvind-Srinivasan commented on control/include/robocup/modules/MotionControlModule.hpp
> +#include <algorithm>
This has a weird include formatting

2022-05-13 09:35 UTC, Arvind-Srinivasan commented on control/mtrain/.gitignore
> +*.kdev4
This whole file shouldn't exist

2022-05-13 09:35 UTC, Arvind-Srinivasan commented on control/mtrain/API/cpp/CMakeLists.txt
> +aux_source_directory(Src/ API_CPP_SRC)
The "cpp" folder should be deprecated with instead just an API_SRC folder

2022-05-13 09:35 UTC, Arvind-Srinivasan commented on control/mtrain/doc/DoxygenLayout.xml
> +<doxygenlayout version="1.0">
Maybe test to see how we can integrate this into the larger robocup firmware doxygen setup

2022-05-23 18:27 UTC, closed without merging

2022-05-23 18:28 UTC, kasohrab commented
being done in #157 instead, but the description I will leave here.

2022-05-25 02:16 UTC, Arvind-Srinivasan commented
@kasohrab are we reopening this now 156 is working?

2022-05-25 02:44 UTC, kasohrab commented
> @kasohrab are we reopening this now #157 is working?

so on this branch radio wouldn't initialize. I'm not sure what of your changes would cause that and it's hard to debug currently. Also, I'd like to start moving to fix scheduling stuff as soon as I can. 

I was thinking to slowly add some of your tweaks over time until something breaks. But if you know what could have caused that then we could reopen this?